function [EI,JI]=josephus_and_encrypt(I,encryption_key,jump,u,v,msb)
    % JI: image with only Josephus traverse
    % EI: image with Josephus traverse and encryption
    [m,n]=size(I);
    
    
    % scramble using Josephus traverse
    hor_num=floor(m/u);
    ver_num=floor(n/v);
    
    B=1:hor_num*ver_num;
    Bp=josephus(B,jump);
    
    JI=I;
    len_key=length(encryption_key);
    
    for i=1:hor_num*ver_num
       ind=Bp(i);
       [x,y] = ind2sub([hor_num,ver_num],ind);
       [xi,yi] = ind2sub([hor_num,ver_num],i);
       tmp=I((x-1)*u+1:x*u,(y-1)*v+1:y*v);
       % permute within differendt blocks with different keys
       % different keys are generated by strcat(...)
       ptmp=permute_within_block(tmp,strcat(encryption_key,encryption_key(mod(ind,len_key)+1)));
       JI((xi-1)*u+1:xi*u,(yi-1)*v+1:yi*v)=ptmp;
    end
    
    EI=encrypt_with_mMSB(JI,encryption_key,msb);
    
    
    
%     EI=JI;
    
end